// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBa6bDxHwMZ_MmGxmioO6okJ9ArJwJUx0',
    appId: '1:612944093237:web:9eb5c6e96ee05ad6b2d17c',
    messagingSenderId: '612944093237',
    projectId: 'edu-app-flutter-a7773',
    authDomain: 'edu-app-flutter-a7773.firebaseapp.com',
    storageBucket: 'edu-app-flutter-a7773.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngov3fwF7J4NCpR-J77kt7T-wx5E6p9E',
    appId: '1:612944093237:android:07af93a9161cbad9b2d17c',
    messagingSenderId: '612944093237',
    projectId: 'edu-app-flutter-a7773',
    storageBucket: 'edu-app-flutter-a7773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXz0tXiF7tOo68gydVU2W2RGxBpypRlm4',
    appId: '1:612944093237:ios:c06e2498aa005cc1b2d17c',
    messagingSenderId: '612944093237',
    projectId: 'edu-app-flutter-a7773',
    storageBucket: 'edu-app-flutter-a7773.appspot.com',
    iosClientId: '612944093237-pub5dqsvus7ncm8a1at490b8hdci43e3.apps.googleusercontent.com',
    iosBundleId: 'com.dbolshakov.eduApp',
  );
}
